# モジュール

これまでも、random, matplotlib などのモジュールを利用してきました。モジュールに定義された関数などは、import することにより自分が今書いているプログラムの中で利用することができます。モジュールは，.py という拡張子を持ったプログラムファイルを作ることにより定義できます。自分でモジュールを定義して利用しながら、この機能について、詳しくみていきます。

### モジュールの定義と利用

これまで、プログラムを jupyter-lab の notebook の中に書いてきましたが、プログラムをファイルに書いておいて実行することができます。プログラム・ファイルは、 "factorial.py" のように、.py という拡張子をつけておきます。例えば、次の内容のファイルを factorial.py という名前で作りましょう。jupyter-lab では File の New の TextFile で作れます。

これで、factorial モジュールができました。
```
import factorial 
```
によって fctorial を import すると、factorial.py に書かれた内容が実行されます。すなわち、a に 1 が代入され、fact 関数が定義され、fact(100) の値が計算されて、fact100 変数に代入されます。また、fact(10) の値が表示されます。それぞれのモジュールは、そのモジュールの名前空間を持っています。a, fact, fact100 という名前は、factorial モジュールの名前空間に登録されます。そして、import したことによって、今実行している "グローバルの名前空間"には、factorial という名前で、このモジュールが登録されます。

In [ ]:
import factorial

名前空間に登録されているものは、dir() で見ることができました。
dir の引数にモジュールを与えると、そのモジュールの名前空間を見ることができます。

**練習問題** factorial をimport し、
グローバルの名前空間、および、factorial モジュールの名前空間に登録されている名前をみよう。特に，a, fact, fact100 が factorial に登録されていることを確認しよう。fact(20) を計算しよう。

In [ ]:
print(factorial)
dir()

In [ ]:
dir(factorial)

In [ ]:

factorial.fact(20)

In [ ]:
factorial.a

In [ ]:
factorial.fact100

このように、factorial モジュールには fact100 が登録されています。モジュールなどの名前空間に登録されている値は
```
モジュール名.名前
```
でアクセスします。
`factorial.fact(10)`
という形で factorial に登録された fact 関数を呼び出せるし、fact100 の値は、
`factorial.fact100`
で見ることができます。

今は、グローバルな名前空間には factorial.py で定義されたモジュール全体を取り込みましたが、他のモジュールの中の個々の名前を指定してその名前だけを取り込むこともできます。
(同じモジュールを何回も import しても、そこに書かれている内容が実行されるのは1回だけです。よって、今回は fact(10) の値は表示されません。)

In [ ]:
from factorial import fact100, fact

こうすると、fact100 と fact が直接グローバルな名前空間に登録されます。(dir で確認しよう。）よって，モジュール名をつけずに、fact100, fact という名前だけでアクセスができます。
また、import する時に、名前を指定することもできます。

In [ ]:
from factorial import fact100 as largenumber
largenumber

他のモジュールを import するというのは、どのモジュールにおいても行えます。例えば，factorial.py を作成するのに，他のモジュールを用いているとしたら factorial.py の中で，import 文が書かれています。その時には，その import 文が実行されると，factorial の名前空間に，その import されたモジュールが登録されることになります。

jupyter-lab では，それぞれの .ipynb ファイルごとに，グローバルな名前空間があって，そこでプログラムを実行していました。実は，これも一つのモジュールであり，グリーバルな名前空間と呼んでいたのは，そのモジュールの名前空間です。この，プログラムの実行を開始するモジュールを，main モジュールといいます。main モジュールには，`__main__` という名前がついています。 

プログラムの実行の各時点において，その時に実行しているコードが定義されているモジュールがあります。そのモジュール名は，`__name__` 変数の値として見ることができます。

In [ ]:
__name__

In [ ]:
factorial.__name__

**練習問題** factorial.py の fact 関数の中に，```print(__name__)``` を挿入して fact 関数を実行し，その時点でのモジュール名が　factorial であることを確認しよう。　

### モジュールの直接実行

モジュールは、jupyter-lab などのインタープリタを介せずに、直接実行することができます。そのファイルを vscode で実行することもできますし，また，コマンドプロンプトで
```
python factorial.py
```
とすることによっても実行できます。（この実行方法は OS や環境により異なります。）
実行すると、print 文が実行されるので　3628800　が表示されるはずです。

このように，モジュールには，直接実行するのと，他のモジュールからインポートするのと，2つの利用方法があります。今，どちらの方法で利用されているかを調べることができれば，直接実行の時だけにあることを実行させることが可能になります。

それには，`__name__` の値を見て，それが__main__ の時のみ実行するようにすればいいです。この値は，モジュール名が入りますが，直接実行した場合には，モジュール名は`__main__` となっています。

**練習問題** factorial.py の print(fact(10)) が、直接実行した時だけ実行されるようにしましょう。また，
```
if (__name__ == "__main__"):
    print(fact(int(input("数を入力してください:"))))
```
をいれて，直接実行した時には，キーボードからの入力をもらって，その値の fact を計算するようにしましょう。ここで，input 関数は，引数で与えられた文字列を画面出力して，入力を待ち，入力された文字列を返す関数です。

In [ ]:
x = int(input("次の数は？"))
x

## パッケージ

複数のモジュールがまとまって、一つの機能を提供することがあります。
そういう時には、それらのモジュールのファイルは一つのフォルダーに置きます。
そのフォルダーのことを、パッケージといい、プログラム中では、パッケージに属するモジュールは、
```
パッケージ名.モジュール名
```
で指定します。パッケージのフォルダには、__init__.py という名前で、そのパッケージを読み込んだ時に行う
初期化のプログラムを書いて置きます。何もすることがなければ、空で構いません。


例えば，matplotlib は次のように import していました。ここでは、matplotlib はパッケージ名で、matplotlib.pyplot がモジュール名です。ややこしいですが、matplotlib モジュールの pyplot という変数や関数を import しているのではありません。

In [ ]:
import matplotlib.pyplot as plt

### モジュールに定義された名前

今まで、jupyter-lab で用いられる名前空間をグローバルな名前空間と呼んできましたが、上に書いたように、これも一つのモジュールです。よって、これも含めて、これからはグローバルな名前空間ではなく、モジュールの名前空間と呼ぶことにします。
今までグローバル変数と呼んでいたのは、 main モジュールの変数ですし、a は、factorial モジュールの変数です。a には、a という名前だけではアクセスできませんが、factorial.a という
```
モジュール名.変数名
```
という名前でなら、factorial を import しているモジュールからアクセスできます。
今度は、factorial を短い名前 f で import しましょう。


In [ ]:
import factorial as f
print(f.a)
f.a = 2
f.fact(3)

f.a は、代入ができてしまいます。それによって、f.fact の結果も変わってきます。他のモジュールの変数の値を変えるのは、お行儀のいいことではないので勧めませんが、このように，python では，モジュールに属する変数に，そのモジュールからしかアクセスできないといった、アクセス制限をつける機能は存在しません。

モジュールの名前空間は、辞書(dict) を用いて実現されています。つまり、それぞれのモジュールは、名前空間を実現するための辞書を持っています。この辞書には，そのモジュールで定義された変数（に代入された値）と，そのモジュールで定義された関数，それに，そのモジュールで import した名前が登録されています。

モジュールに定義されている名前の一覧は、
```
dir(モジュール名)
```
で得ることができます。

In [ ]:
dir(f)

モジュールで定義された値や，関数とモジュールの doc string の内容は、help 関数で見ることができます。

In [ ]:
help(f)

`__名前__` という形の名前は、特殊属性と呼ばれるものであり、システム的な意味があります。

繰り返しになりますが，DATA に書かれているものも FUNCTIONS に書かれているものも、この辞書に登録された要素です。
この、辞書による名前空間を意識すると、python が分かりやすくなります。

関数の値も書き換えられます。もちろん、このようなことをするべきではありませんが、python は、こんなことが出来てしまう言語です。

In [ ]:
f.fact=lambda x:x 
f.fact(10)

In [ ]:
f.fact(10)

In [ ]:
import random
random.randrange = lambda x:1
random.randrange(10)

In [ ]:
random.b = 3

# NumPy

NumPy は、数値計算を効率よく行うためのライブラリです。Python 本体とは別に開発されたものですが、anaconda を用いて Python をインストールすると、最初からこのモジュールは入っています。（もし入っていなければ、pip でインストールします。）

NumPy の最大の特徴は、多次元配列の型をもっており、効率的に行列演算などが行えることです。1 次元の配列に相当するものは，python でもリストで実現できます。しかし，python のリストは汎用性はありますが，その処理は非常に低速であり，科学計算のプログラムの中でリスト処理を行うのはおすすめしません。また，説明を省略しましたが python には array という型があり，それなりに高速な処理ができます。Numpy は，それと比べても高速な行列演算を実現しています。

numpy は、np という名前でインポートするのが普通です。

### 配列

NumPy では、高次元の配列も使うことができます。
1次元配列はベクトル、2次元配列は行列を表現するのに用いられます。一般に配列は、数学でテンソルと呼ばれるものを表現しています。

Numpy の配列は、内容のリストを引数として作ります。

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)
a

[1 2 3]


array([1, 2, 3])

このように，NumPy 配列は，ndarray と呼ばれます。nd というのは，複数次元という意味です。の2次元以上の配列も、リストのリストを引数として与えれば、同様に作れます。


In [ ]:
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(b)
display(b)
b

In [ ]:
c = np.array(["Hello", 123.5])

In [ ]:
print(c)
c

配列の中身は int, float, char, complex などの型をとります。この型は，python の型とか関係なく，むしろ，NumPy ライブラリが実現されている C 言語の型に対応しています(後述)。配列の中身は全て同じ型でなくてはなりません。配列の初期値として int と float が与えられたら float にそろえられます。
NumPy行列の中身の表記では、2.0 の 0 は省略されます。

In [ ]:
c = np.array([2/3, 2, 3])
c       

次のような作り方もできます。


In [ ]:
d = np.zeros(4)
e = np.ones(3,dtype=int)
f = np.reshape(range(12),(3,2,2))
print(d)
print(e)
print(f)


In [ ]:
f[2][1][1] = 1
f

大きさ n の単位行列は、np.identity(n) で作ることができます。

In [ ]:
x=np.identity(3)
print(x)
print(x.dtype)

行列を画面表示するのに、print 文では、指数表示と小数点表示が
まざって、見にくくなることがあります。表記を制限するのに、
np.set_printoptions
を用います。例えば、次の設定で、全て少数以下3桁の小数点表示になります。

In [ ]:
x = np.array([[np.pi,np.pi]])
print(x)
np.set_printoptions(precision=3, suppress=True)
print(x)

複素数のところで，オブジェクトがデータ属性を持てることを述べました。
行列は、型およびサイズを dtype, shape 属性としてもっています。
属性の値は、
```
オブジェクト.属性名
```
でアクセスできます。

In [ ]:
print(a, b, c)

In [ ]:
(a.shape, b.shape, c.shape)

In [ ]:
(a.dtype, b.dtype, c.dtype)

In [ ]:
e = np.ones(3, dtype=complex)
e.dtype

int でなくて int64 となっていますが、NumPy ライブラリは C 言語で実現されており、これらの型は，C 言語での実現に対応した型です。int64 は 64 ビットで表現された整数なので，大きな数は扱えません。

In [ ]:
a[0] = 1000000000000000000000

### 配列の演算

リストと違って、NumPy の配列は、容易に要素ごとの演算ができます。
通常の +, * は、要素ごとの演算になります。片方の次元が低ければ、同じ要素をコピーして次元を合わせたものを作って行われます。

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [4]:
[1,2,3] + [3,4,5]

[1, 2, 3, 3, 4, 5]

In [5]:
a = np.array([1,2,3])
c = 2
print(a + c)
print(a * c)

[3 4 5]
[2 4 6]


In [11]:
#次元をあわせるには、
#[2,1,0] を2次元に合わせるには、[[2,1,0]] に合わせられる。
print(np.array([2,1,0]).reshape(1,3))  # こっち
print(np.array([2,1,0]).reshape(3,1))  #こちらではない

[[2 1 0]]
[[2]
 [1]
 [0]]


In [12]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
e = np.array([[1,0,0],[0,2,0],[0,0,3]])
print(d)
print(e)
print(d + e)   # 要素ごと
print(d + np.array([2,1,0])) # 次元を合わせてから実行。
print(d + [2,1,0]) # リスト[2,1,0] は np.array に自動変換される
print(d + 2)  # 全要素に
# 掛け算も同様。

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[ 2  2  3]
 [ 4  7  6]
 [ 7  8 12]]
[[3 3 3]
 [6 6 6]
 [9 9 9]]
[[3 3 3]
 [6 6 6]
 [9 9 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


2次元配列の行列としての積は、@ または np.dot により行います。* は要素ごとの演算になるので注意してください。

In [13]:
print(d@e)
print(np.dot(e,d))

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


(n, m)行列と (m, k)行列の積は (n,k)行列になります。

In [ ]:
f = np.array([[1,0,0],[0,2,0]])

print(np.dot(f,e))
# print(np.dot(e,f)) これはエラーとなる

行列の積を確認しましょう。


**練習問題10** 行列 x, y が与えられた時，それの積 x @ y を求めるプログラム prod を自分で書いてみよう。，x の列と y の行の個数が合わなかったら，None を返すようにしよう。
x @ y と比較して，同じ計算が行われていることを確認しよう。



ベクトルの場合には、@  や np.dot は内積になります。

In [14]:
print(np.dot([1,2,3],[4,5,6]))
np.array([1,2,3])@np.array([4,5,6])

32


32

最大の要素は，np.max 関数でとってこれます。

In [15]:
f = np.array([[1,2,3],[4,5,6]])
np.max(f)

6

### 行列の中身、部分行列、行や列の追加、削除

リストにおけるインデックスやスライスの指定方法が多次元に拡張されて、 np.array にも適用できます。(n,m) 行列の行は 0 から n-1, 列は0 から m-1 にインデックスされていることに注意してください。

In [17]:
a = np.reshape(range(12),(3,4))
print(a)
b = a[1,3] #a[1][3] でも同じ意味になる
c = a[1:3,1:4] #a[1:3][1:4] だと、(a[1:3])[1:4] の意味になる。
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7
[[ 5  6  7]
 [ 9 10 11]]


行と列の片方だけスライス、片方だけインデックスを指定すると、行や列を取り出せます。

In [18]:
print(a[1,:]) # :　は、全体というスライスになるのでした。
print(a[:,2])

[4 5 6 7]
[ 2  6 10]


スライスは，新たな配列を作ったのではなく，元の配列の一部分を表しています。これを，ビューといいます。よって，スライスとしてできた配列は元の配列のビューなので，その内容を書き換えると，元の配列が書き換わります。

In [19]:
c

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
c[0,0]=-1
a

スライスへの代入もできます。

In [20]:
import numpy as np
x = np.reshape(range(12),(3,4))
print(x)
y = np.identity(2)
x[1:,1:3] = y
print(x)
x[0,1:3] = np.array([-1,-1])
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  1  0  7]
 [ 8  0  1 11]]
[[ 0 -1 -1  3]
 [ 4  1  0  7]
 [ 8  0  1 11]]


### 列や行の削除

In [ ]:
print(a)
print(np.delete(a,1,0)) #1 行目削除、最後の 0 は行を意味する
print(np.delete(a,2,1)) #2 列目削除、最後の 1 は列を意味する。

行や列の削除を行うと，新しい配列が作られ，元の行列との要素の共有は行われません。

### ファンシーインデックス

行、列、それぞに対して、入れ替え方を、リストにして、スライスと同様に指定してやれば，
行列の行や列を自由に入れ替えることができます。
元の行列との要素の共有は行われません。

In [21]:
a = np.reshape(range(12),[4,3])
print(a)
b = a[[0,3,2,1],:]
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]]


### 乱数行列などのライブラリ

np ライブラリには，様々なライブラリが用意されています。これらを ndarray と一緒に用いることにより，効率的な処理が可能となります。例えば，np.random モジュールの random を用いると，乱数からなる配列が作れます。詳しくは、np.random の doc-string, np.random.uniform の doc-string などをみてください。

In [22]:
np.random.random(size=(2,3))

array([[0.23112871, 0.80258908, 0.07729147],
       [0.61921509, 0.64725033, 0.62226545]])

このような処理は，全て，python で for 文などを用いて書くことができます。しかし，python で書かれた処理と NumPy で書かれた処理とでは，実行時間がかなり違います。実行時間を気にする処理は，できるだけ，for 文などは使わずに NumPy の中だけで書くようにする必要があります。

### 行列式

np.linalg モジュールに、行列の行列式(det)、逆行列(inv)などの関数があります。このようなライブラリは高速に動作するし、多くの利用の中で正確さが保証されています。ここでは、プログラミングの演習として、これらの計算を行うプログラムを作成しましょう。

**練習問題** n 次正方行列 $X=(x_{i,j})$　の行列式は、この行列により行われる一次変換が、2次元なら面積、3次元なら体積を何倍するかという値です。これが 0 なら、一次変換の像は面積が0、すなわち、次元が低くなります。行列式の値は，

$$\sum_{\sigma \in \mathrm{Aut}(n)} \mathrm{sgn}(\sigma)\prod_{i=1}^n x_{i, \sigma(i)}
$$
で計算できます。ここで、$\mathrm{Aut}(n)$ は、$[0,1,..,n-1]$ の置換全体を表しました。これは、permutations という名前ですでにプログラムしました。
$\mathrm{sgn}$ は、置換 sgn が偶置換なら 1, 奇置換なら -1 という値です。これは、与えられた置換 $\sigma=[a_0,...,a_{n-1}]$ が、偶数個の互換(2つの数の入れ替え) でできてるか、奇数個でできてるかということですが、$\sigma$ を2つづつ要素を入れ替えてソートする時に、入れ替えを偶数回行うか奇数回行うかと同じ値ですから、ソートのプログラムに修正を加えれば求まるはずです。素直にこの式で行列式を求められそうでが、これはプログラムが面倒そうです。これは、余力がある時だけにして、次の問題を先に考えましょう。

**練習問題30** n 次正方行列 $X=(a_{i,j})$ に対し、i 行目とj 列目を除いた n-1 次正方行列の行列式に $(-1)^{i+j}$ を掛けたものを、$\Delta_{i,j}$ と書いて、$X$ の余因子といいます。
$X$ の行列式は、各 j に対して，余因子を用いて
$$
\sum_{i=0}^{n-1}a_{i,j} \Delta_{i,j}
$$
と等しくなります。これなら、行列式を求める関数 det 関数は、再帰呼び出しで素直に書けそうです。書いてみましょう。そして、ライブラリに置かれている関数と比較しましょう。
また、%time を用いて、両者の計算時間も比較しましょう。


### 逆行列(提出課題)


行列の逆行列を求める方法に、はき出し法があります。これで、逆行列を求めてみましょう。


**練習問題** $0 \leq a, b <n$ に対して、 $(n,n)$ 行列に左から掛けると $a$ 行目 と $b$ 行目をひっくり返した行列になる行列を返す関数 p(n, a, b) を定義しよう。

**練習問題** $0 \leq  a <n$ と 実数 $r$ に対して、 $(n,n)$ 行列に左から掛けると $a$ 行目 を $r$ 倍した行列になる行列を返す関数 q(n, a, r) を定義しよう。

**練習問題** $0 \leq  a, b <n$ と 実数 $r$ に対して、 $(n,n)$ 行列に左から掛けると $a$ 行目 を $r$ 倍したものを $b$ 行目に加えた行列ができるような行列を返す関数 r(n,a,b,r) を定義しよう。

**練習問題** p, q, r を用いて、掃き出し法（ガウスの消去法）により、$(n,n)$ の正方行列 $X = (x_{i,j})$ の逆行列を求めるメソッド inv(x) を作成しよう。正則でなければ、None を返すようにしよう。ランダムな行列に対して逆行列を作って掛けることにより、正しさを確認しよう。また、ライブラリ関数の結果と比べてみよう。

1. まず、$X$ と単位行列 $I$ を用意する。

1. $X$ が単位行列になるように p, q, r で作った基本変換行列を X に左から掛ける。

2. それと同時に，I にも同じ行列を左からかけていく。

逆行列を求める関数 inv が作れたかどうかは、例えば、つぎのようにして確認できる。
```
x=np.random.random([9,9])
np.set_printoptions(precision=3, suppress=True)
print(x)
y = inv(x)
print(y)
print(x@y)
```

**練習問題** p, q, r の操作を行列の掛け算で行うのは、途中で無駄な行列を作ることになり、効率がよくない。行列の掛け算を行うのではなく、p, q, r を、引数としてとった行列 x 自体を書き換えるようにプログラムを書き換えよう。x に対し、x の右に $n \times n$ の単位行列を加えた、$n \times 2n$ の行列を作ろう。それに対し、p, q, r に対応する操作で、行列そのものを書き換える操作 p, q, r を作ろう。それで、左半分を単位行列に変化するような操作を行うと、右半分は、逆行列になっているはずである。

実数行列の表記を見やすくするには，次のようにしてprecision を設定しておくといいです。

In [ ]:
x = np.random.random([3,3])
np.set_printoptions(precision=3, suppress=True)

In [ ]:
y=np.identity(3)

In [ ]:
print(x)
print(y)

行列に一部に他の行列をコピーするのは，次のようにかけます。

In [ ]:
z = np.zeros(shape=(3,6))

In [ ]:
z[0:3,0:3] = x

In [ ]:
z[0:3,3:6] = y
z