# モジュール

これまでも、random, matplotlib などのモジュールを利用してきました。モジュールに定義された関数などは、import することにより自分が書いているプログラムの中で利用することができました。自分でモジュールを定義して利用しながら、この機能について、詳しくみていきます。

### モジュールの定義と利用

これまで、プログラムを jupyter-lab の中に書いてきましたが、ファイルに書いておいて実行することができます。ファイルを作る時には、 "factorial.py" のように、.py という拡張子をつけておきます。例えば、次の内容のファイルを factorial.py という名前で作りましょう。jupyter-lab では File の New の TextFile で作れます。

これで、factorial モジュールができました。
```
import factorial 
```
によって fctorial を import すると、factorial.py に書かれた内容が実行されます。すなわち、a に 1 が代入され、fact 関数が定義され、fact(100) の値が計算されて、fact100 変数に代入されます。また、fact(10) の値が表示されます。それぞれのモジュールは、独自の名前空間を持っています。これらの名前は、factorial モジュールの名前空間に登録されます。そして、今実行している "グローバルの名前空間"には、import によって、factorial という名前で、このモジュールが登録されます。

名前空間に登録されているものは、dir() で見ることができました。
dir の引数にモジュールを与えると、そのモジュールの名前空間を見ることができます。

**練習問題** factorial をimport し、
グローバルの名前空間、および、factorial モジュールの名前空間に登録されている名前の一覧を得よう。fact(20) を計算しよう。

In [1]:
import factorial
print(dir())
print(dir(factorial))
factorial.fact(20)

3628800
['In', 'Out', '_', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_ih', '_ii', '_iii', '_oh', 'exit', 'factorial', 'get_ipython', 'quit']
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'a', 'fact', 'fact100']


2432902008176640000

このように、factorial モジュールには fact100 が登録されています。モジュールなどの名前空間に登録されている値は
```
モジュール名.名前
```
でアクセスします。
`factorial.fact(10)`
という形で factorial fact 関数は呼び出せるし、fact100 の値は、
`factorial.fact100`
で見ることができます。

In [3]:
print(factorial.fact100)
factorial.fact(10)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


3628800

今は、グローバルな名前空間には factorial だけを取り込みましたが、他のモジュールの中の名前を指定してその名前だけを取り込むこともできます。
(同じモジュールを何回も import しても、そこに書かれている内容が実行されるのは1回だけです。よって、今回は fact(10) の値は表示されません。)

In [2]:
from factorial import fact100, fact

こうすると、モジュール名をつけずに、fact100, fact という名前だけでアクセスができます。
また、import する時に、名前を指定することもできます。

In [3]:
from factorial import fact100 as largenumber
largenumber

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

### モジュールの直接実行

モジュールは、jupyter-lab などのインタープリタを介せずに、直接実行することができます。コマンドプロンプトで
```
python factorial.py
```
により実行できます。（この実行方法は OS や環境により異なります。）
実行すると、print 文で　3628800　が表示されるはずです。この print 文は、直接実行した時だけ実行したいとしましょう。直接実行した時と、import された時と比べると、import された時のモジュールの名前空間には `__name__` という変数にはモジュール名が入っているのに対し、直接実行された時には `__main__` という文字列が入っているという違いがあります。これで、直接実行された時だけ、あることを実行するという指定ができます。次の一文を、factorial.py に入れてみましょう。


In [5]:
if (__name__ == "__main__"):
    print(fact(20))


2432902008176640000


他のモジュールを import するというのは、どのモジュールからでも行えます。ですから、factorial.py に相当するモジュールが、他のモジュールを input して作られていることもあります。プログラムの実行のために最初に起動されたモジュールは main モジュールといいます。上の例で、他のモジュールから import されたのか、それとも直接実行されたのかを調べるのに　__name__ 変数の値が __main__ かどうかで調べました。__name__ は、メインモジュールでは main, 他のモジュールから import された時にはそのモジュール名が代入されます。直接実行されたモジュールは main モジュールですが、jupyter-lab のトップレベルのモジュールも main モジュールもそうです。

## パッケージ

複数のモジュールがまとまって、一つの機能を提供することがあります。
そういう時には、それらのモジュールのファイルは一つのフォルダーに置きます。
そのフォルダーのことを、パッケージといい、プログラム中では、パッケージに属するモジュールは、
```
パッケージ名.モジュール名
```
で指定します。パッケージのフォルダには、__init__.py という名前で、そのパッケージを読み込んだ時に行う
初期化のプログラムを書いて置きます。何もすることがなければ、空で構いません。


matplotlib は次のように import していました。ここでは、matplotlib はパッケージ名で、matplotlib.pyplot がモジュール名です。ややこしいですが、matplotlib モジュールの pyplot という変数や関数を import しているのではありません。

In [10]:
import matplotlib.pyplot as plt

### モジュールに定義された名前

今まで、jupyter-lab のトップレベルで用いる名前空間をグローバルな名前空間と呼んできましたが、上に書いたように、トップレベルも一つのモジュールです。よって、これも含めて、これからはグローバルな名前空間ではなく、モジュールの名前空間と呼ぶことにします。
今まで変数と呼んでいたのは、main モジュールの前章までに現れていたのは main モジュールの変数ですし、a は、factorial モジュールの変数です。a には、a という名前だけではアクセスできませんが、
```
モジュール名.変数名
'''
という名前でなら、factorial を import しているモジュールからでもアクセスできます。
今度は、factorial を短い名前 f で import しましょう。


In [1]:
import factorial as f
print(f.a)
f.a = 2
f.fact(1)

3628800
1


2

f.a は、代入ができてしまいます。それによって、f.fact の結果も変わってきます。他のモジュールの変数の値を変えれるのは、お行儀のいいことではありませんが、モジュールの変数はこのモジュールだけしかアクセスできないといった、アクセス制限の機能がないので、できてしまいます。

モジュールの名前空間は、辞書(dict) を用いて実現されています。つまり、それぞれのモジュールは、名前空間を実現するための辞書を持っています。
これまでグローバルな名前空間の変数をグローバル変数と言っていましたが、グローバル変数は、モジュールの辞書にキーとして登録されている名前です。
この名前空間には、そのモジュールで定義された関数も登録されています。

モジュールに定義されている名前の一覧は、
```
dir(モジュール名)
```
で得ることができます。

In [4]:
dir(f)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'a',
 'fact',
 'fact100']

__名前__ という名前は、特殊属性と呼ばれるものであり、システム的な意味があります。
また、その値は、help 関数で見ることができます。

In [5]:
help(f)

Help on module factorial:

NAME
    factorial

FUNCTIONS
    fact(n)

DATA
    a = 2
    fact100 = 933262154439441526...0000000000000000000

FILE
    /Users/tsuiki/Dropbox/lecture/python/factorial.py




fact などの関数も、この辞書に登録された要素です。
関数は FUNCTIONS, 変数が DATA となっていますが、
このように、今まで関数や変数と言ってきたものは、辞書にその名前で登録された関数やデータに
他なりません。この、辞書による名前空間を意識すると、python が分かりやすくなります。

関数の値も書き換えられます。もちろん、このようなことをするべきではありませんが、python は、こんなことが出来てしまう言語です。

In [6]:
f.fact=lambda x:x 
f.fact(10)

10


TypeError: 'int' object is not callable

In [24]:
import random
random.randrange = lambda x:x
random.choice(10)

10

# NumPy

NumPy は、数値計算を効率よく行うためのライブラリです。Python 本体とは別に開発されたものですが、anaconda を用いて Python をインストールすると、最初からこのモジュールは入っています。（もし入っていなければ、pip でインストールします。）

NumPy の最大の特徴は、多次元配列の型をもっており、効率的に行列演算などが行えることです。1 次元の配列は、リストとよく似ています。また、説明を省略しましたが Python 自身が array という型をもっています。それらと混同しないようにしてください。

numpy は、np という名前でインポートするのが普通です。

### 配列

NumPy では、高次元の配列も使うことができます。
1次元配列はベクトル、2次元配列は行列を表現するのに用いられます。一般に配列は、数学でテンソルと呼ばれるものを表現しています。

配列は、内容のリストを引数として作ります。

In [17]:
a = np.array([1,2,3])
a

NameError: name 'np' is not defined

2次元以上の配列も、リストのリストを引数として与えれば、同様に作れます。


In [11]:
b = np.array([[1,2,3],[4,5,6]])

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

次のような作り方もできます。

配列の中身は、int, float, char, complex など、どんな型でもとれます。配列の中身は全て同じ型です。初期値として int と float が与えられたら float にそろえられます。
numpy行列の中身の表記では、2.0 の 0 は省略されます。

In [13]:
c = np.array([1.5, 2, 3])
c       

array([1.5, 2. , 3. ])

次のような作り方もできます。dtype については後でふれます。
より詳しくは、下の np.zeros セルの np.zeros などの後ろで shift+tab を押して doc-string を出してみてください。

In [14]:
d = np.zeros(4)
e = np.ones(3,dtype=int)
f = np.reshape(range(12),(3,4))
print(d)
print(e)
print(f)

[0. 0. 0. 0.]
[1 1 1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


行列などのオブジェクトは、属性を持つことができます（後述）。
行列は、型およびサイズを dtype, shape 属性としてもっています。
属性の値は、
```
オブジェクト.属性名
```
でアクセスできます。

In [15]:
(a.shape, b.shape, c.shape)

((3,), (2, 3), (3,))

In [16]:
(a.dtype, b.dtype, c.dtype)

(dtype('int64'), dtype('int64'), dtype('float64'))

int でなくて int64 となっていますが、NumPy ライブラリは C 言語で実現されており、C 言語でのデータの型が分かるようになっています。

### 配列の演算

リストと違って、NumPy の配列は、容易に行列演算ができます。
通常の +, * は、要素ごとの演算になります。片方の次元が低ければ、同じ要素をコピーして次元を合わせて行います。

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = 2
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [18]:
print(a + c)
print(a * c)

[3 4 5]
[2 4 6]


In [19]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
e = np.array([[1,0,0],[0,2,0],[0,0,3]])
print(d + e)   # 要素ごと
print(d + [2,1,0]) # 各行に。[2,1,0] は np.array に自動変換
print(d + 2)  # 全要素に
# 掛け算も同様。

[[ 2  2  3]
 [ 4  7  6]
 [ 7  8 12]]
[[3 3 3]
 [6 6 6]
 [9 9 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


2次元行列の積は、@ または np.dot により行います。

In [21]:
print(d@e)
print(np.dot(e,d))

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
[[ 1  4  9]
 [ 2  6 12]]


(n, m)行列と (m, k)行列の積は (n,k)行列になります。

In [75]:
f = np.array([[1,0,0],[0,2,0]])

print(np.dot(f,e))
# print(np.dot(e,f)) これはエラーとなる

[[1 0 0]
 [0 4 0]]


ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

ベクトルの場合には、@  や np.dot は内積になります。

In [78]:
print(np.dot([1,2,3],[4,5,6]))
np.array([1,2,3])@np.array([4,5,6])

32


32

### 行列の中身、部分行列、行や列の追加、削除

リストにおけるインデックスやスライスの指定方法が多次元に拡張されて、 np.array にも適用できます。(n,m) 行列の行は 0 から n-1, 列は0 から m-1 にインデックスされていることに注意してください。

In [99]:
a = np.reshape(range(12),(3,4))
print(a)
b = a[1,3] #a[1][3] でも同じ意味になる
c = a[1:3,1:4] #a[1:3][1:4] だと、(a[1:3])[1:4] の意味になる。
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7
[[ 5  6  7]
 [ 9 10 11]]


行と列の片方だけスライス、片方だけインデックスを指定すると、行や列を取り出せます。

In [103]:
print(a[1,:]) # :　は、全体というスライスになるのでした。
print(a[:,2])

[4 5 6 7]
[ 2  6 10]


列や行の削除

In [111]:
print(a)
print(np.delete(a,1,0)) #1 行目削除、最後の 0 は行を意味する
print(np.delete(a,2,1)) #2 列目削除、最後の 1 は列を意味する。

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]


### 乱数行列などのライブラリ

ライブラリが用意されています。np.random モジュールにライブラリが用意されています。詳しくは、np.random の doc-string, np.random.uniform の doc-string などを表示してみてください。

In [81]:
np.random.random(size=(2,3))

array([[0.60630891, 0.75035886, 0.58436182],
       [0.36142015, 0.97298324, 0.19546618]])

### 行列式

np.linalg モジュールに、行列の行列式(det)、逆行列(inv)などの関数があります。このようなライブラリは高速に動作するし、多くの利用の中で正確さが保証されています。ここでは、プログラミングの演習として、これらの計算を行うプログラムを作成しましょう。

**練習問題** n 次正方行列 $X=(x_{i,j})$　の行列式は、この行列により行われる一次変換が、2次元なら面積、3次元なら体積を何倍するかという値です。これが 0 なら、一次変換の像は面積が0、すなわち、次元が低くなります。

$$\sum_{\sigma \in \mathrm{Aut}(n)} \mathrm{sgn}(\sigma)\prod_{i=1}^n x_{i, \sigma(i)}
$$
で計算できます。ここで、$\mathrm{Aut}(n)$ は、$[0,1,..,n-1]$ の置換全体を表しました。これは、permutations という名前ですでにプログラムしました。
$\mathrm{sgn}$ は、置換 sgn が偶置換なら 1, 奇置換なら -1 という値です。これは、与えられた置換 $\sigma=[a_0,...,a_{n-1}]$ が、偶数個の互換(2つの数の入れ替え) でできてるか、奇数個でできてるかということですが、$\sigma$ を2つづつ要素を入れ替えてソートする時に、入れ替えを偶数回行うか奇数回行うかですから、ソートのプログラムに修正を加えれば求まるはずです。素直にこの式で行列式を求められそうでが、これはプログラムが面倒そうです。これは、余力がある時だけにして、次の問題を先に考えましょう。

**練習問題** n 次正方行列 X に対し、i 行目とj 列目を除いた n-1 次正方行列に $(-1)^{i+j}$ を掛けたものの行列式を、$\Delta_{i,j}$ と書いて、$X$ の余因子といいます。
$X$ の行列式は、余因子を用いて、
$$
\sum_{i=0}^{n-1}a_{i,j} \Delta_{i,j}
$$
と等しくなります。これなら、det 関数の再帰呼び出しで素直に書けそうです。


### 逆行列

行列の逆行列を求める方法に、はき出し法があります。これで、逆行列を求めてみましょう。

**練習問題** $0 \leq a, b <n$ に対して、 $(n,n)$ 行列に左から掛けると $a$ 行目 と $b$ 行目をひっくり返した行列になる行列を返す関数 p(n, a, b) を定義しよう。

**練習問題** $0 \leq  a <n$ と 実数 $r$ に対して、 $(n,n)$ 行列に左から掛けると $a$ 行目 を $r$ 倍した行列になる行列を返す関数 q(n, a, r) を定義しよう。

**練習問題** $0 \leq  a, b <n$ と 実数 $r$ に対して、 $(n,n)$ 行列に左から掛けると $a$ 行目 を $r$ 倍したものを $b$ 行目に加えた行列ができるような行列を返す関数 r(n,a,b,r) を定義しよう。

**練習問題** p, q, r を用いて、掃き出し法（ガウスの消去法）により、$(n,n)$ の正方行列 $X = (x_{i,j})$ の逆行列を求めるメソッド inv(x) を作成しよう。正則でなければ、None を返すようにしよう。ランダムな行列に対して逆行列を作って掛けることにより、正しさを確認しよう。また、ライブラリ関数の結果と比べてみよう。

1. まず、$X$ と単位行列 $I$ を用意する。

1. $X$ が単位行列になるように p, q, r で作った基本変換行列を X に左から掛ける。

2. それと同時に，I にも同じ行列を左からかけていく。