In [18]:
def prod(x, y):
    '''行列 x, y の積を計算して返す'''
    (n1,m1) = x.shape
    (n2,m2) = y.shape
    if(m1 != n2):
        return None
    z = np.zeros(shape=(n1, m2))
    for i in range(n1):
        for j in range(m2):
            u = 0
            for k in range(m1):
                u += x[i,k] * y[k,j]
            z[i,j] = u
    return z

x = np.random.random([3,4])            
y = np.random.random([4,5])
print(prod(x,y))
print(x@y)


[[0.5675553  0.83763363 0.70734887 0.9285891  0.5784506 ]
 [1.48907735 1.28861367 1.42468812 2.09638314 1.22713682]
 [0.77640979 0.88649591 1.03020333 1.02679463 0.48499144]]
[[0.5675553  0.83763363 0.70734887 0.9285891  0.5784506 ]
 [1.48907735 1.28861367 1.42468812 2.09638314 1.22713682]
 [0.77640979 0.88649591 1.03020333 1.02679463 0.48499144]]


In [3]:
import numpy as np
a = np.reshape(range(11,20),(3,3))

In [4]:
np.linalg.det(a)

-5.8972434778618435e-15

In [9]:
# 練習問題 30
def mydet (a):
    n,m = a.shape
    if(n==1 or m == 1):
        return(a[0][0])
    u = a[:,1:]
    return (sum ([((-1)**k)*a[k,0]*mydet(np.delete(u,k,0)) 
                  for k in range(n)]))       

In [14]:
# こうやって組んだのは，非常に遅い。ライブラリは C で組んであるので比べ物にならないくらい早い。
# python　は，ちょっとしたプログラムを試しに作る以外では，重要な処理はライブラリとして
# C 言語など組み，それを呼び出す形で処理を書くフロントエンドとしての利用が期待されている。

u=np.random.random([9,9])
%time print(mydet(u))
%time print(np.linalg.det(u))

0.0018072161079971637
CPU times: user 4.11 s, sys: 33.6 ms, total: 4.14 s
Wall time: 4.12 s
0.0018072161079971658
CPU times: user 61 µs, sys: 3 µs, total: 64 µs
Wall time: 66 µs
