In [2]:
import numpy as np
def prod(x, y):
    '''行列 x, y の積を計算して返す'''
    (n1,m1) = x.shape
    (n2,m2) = y.shape
    if(m1 != n2):
        return None
    z = np.zeros(shape=(n1, m2))
    for i in range(n1):
        for j in range(m2):
            u = 0
            for k in range(m1):
                u += x[i,k] * y[k,j]
            z[i,j] = u
    return z

x = np.random.random([3,4])            
y = np.random.random([4,5])
print(prod(x,y))
print(x@y)


[[0.25833884 0.40402503 0.64627181 0.7135669  0.51186028]
 [0.73036791 1.53223621 1.37277678 0.92264057 1.44611931]
 [0.69654907 0.98516048 1.07763553 0.82428156 1.12918359]]
[[0.25833884 0.40402503 0.64627181 0.7135669  0.51186028]
 [0.73036791 1.53223621 1.37277678 0.92264057 1.44611931]
 [0.69654907 0.98516048 1.07763553 0.82428156 1.12918359]]


In [3]:
import numpy as np
a = np.reshape(range(11,20),(3,3))

In [4]:
np.linalg.det(a)

-5.093964465927161e-15

In [5]:
# 練習問題 30
def mydet (a):
    n,m = a.shape
    if(n==1 or m == 1):
        return(a[0][0])
    u = a[:,1:]
    return (sum ([((-1)**k)*a[k,0]*mydet(np.delete(u,k,0)) 
                  for k in range(n)]))       

In [6]:
# こうやって組んだのは，非常に遅い。ライブラリは C で組んであるので比べ物にならないくらい早い。
# python　は，ちょっとしたプログラムを試しに作る以外では，重要な処理はライブラリとして
# C 言語など組み，それを呼び出す形で処理を書くフロントエンドとしての利用が期待されている。

u=np.random.random([9,9])
%time print(mydet(u))
%time print(np.linalg.det(u))

-0.0074619696340269374
CPU times: user 1.71 s, sys: 7.68 ms, total: 1.71 s
Wall time: 1.71 s
-0.00746196963402695
CPU times: user 31 µs, sys: 0 ns, total: 31 µs
Wall time: 31.9 µs
