In [5]:
# 練習問題 50

def p(n,a,b):
    e = np.identity(n)
    q = list(range(n))
    q[a]=b
    q[b]=a
    r = e[q,:]
    return(r)

def q(n,a,r):
    e = np.identity(n)
    e[a,a] = r
    return(e)

def r(n,a,b,r):
    e = np.identity(n)
    e[b,a] = r
    return(e)   


In [6]:
import numpy as np
def inv(x):
    n,_ = x.shape
    e = np.identity(n)
    for i in range(n):
        u = np.argmax(map(abs,x[i:,i]))
        if(abs(x[i,u+i]) <0.001):
            return(None)
        v = p(n,i,u+i);      x = v@x; e = v@e
        v = q(n,i,1/x[i,i]); x = v@x; e = v@e
        for j in range(0,n):
            if(i != j):
                v = r(n,i,j,-x[j,i]); x = v@x; e = v@e
    return(e)
x=np.random.random([9,9])
np.set_printoptions(precision=3, suppress=True)
print(x)
y = inv(x)
print(y)
print(x@y)

[[0.434 0.011 0.557 0.603 0.214 0.995 0.484 0.489 0.749]
 [0.06  0.693 0.516 0.053 0.001 0.733 0.334 0.083 0.987]
 [0.544 0.625 0.962 0.536 0.981 0.971 0.43  0.719 0.496]
 [0.998 0.007 0.353 0.975 0.198 0.946 0.723 0.838 0.966]
 [0.386 0.757 0.863 0.351 0.01  0.71  0.018 0.602 0.652]
 [0.194 0.027 0.09  0.653 0.891 0.197 0.821 0.28  0.132]
 [0.324 0.723 0.105 0.713 0.907 0.66  0.327 0.517 0.861]
 [0.066 0.616 0.221 0.599 0.813 0.532 0.898 0.068 0.67 ]
 [0.49  0.495 0.147 0.777 0.901 0.669 0.67  0.599 0.918]]
[[  48.692 -109.27    -2.893  -52.123   33.512 -136.098 -125.291   93.179
   179.477]
 [ -50.694  105.076    4.895   53.53   -33.443  128.646  121.585  -87.307
  -175.682]
 [  86.372 -183.543   -8.047  -92.562   59.928 -224.753 -211.821  154.216
   304.551]
 [  53.229 -113.292   -6.073  -55.69    37.128 -136.905 -126.525   95.335
   182.706]
 [  41.631  -88.761   -3.117  -44.989   27.692 -109.245 -101.978   74.314
   147.971]
 [ -86.573  186.473    9.092   94.042  -61.318  228.035 