## リストの2つの部分へのきれいな分割

[1,2,3,4] というリストは，[1,4] と [2,3] という2つの部分に分けて，それぞれの和を等しくできる。[1,2,3,4,5,6,7,8] というリストを2つの部分に分けて，それぞれの和だけでなく，2乗の和も等しくできるだろうか。

[1,2,3,...,2^(n+1)] を2つの部分に分けて，和，2乗和，..., n 乗和を等しくする方法があるのだが，n = 1,2,3 くらいまではしらみつぶしで調べられても，そこから先は計算機の能力を超える。3 までで法則性を想像して，それが本当に成り立つかどうか，もっと大きな n まで調べよう。コンピュータでどこまで確かめられるだろうか。

解説：この分割法は，Thue-Morse 列と呼ばれているものである。
Thue-Morse 列がこの性質を満たすことの証明を自分で行うか，net の上で探そう。
Thue-Morse 列の性質はいろんな性質をもっている。n が小さい時に確認したり，自分で証明したりしよう。

In [3]:
def combinations(a, num):  # a: list, num: number
    if (num == 0):
        return [()]
    if (num == len(a)):
        return [tuple(a)]
    return (combinations(a[1:], num) + 
        [(a[0], *b) for b in combinations(a[1:], num-1)])
    
combinations([1,2,3,4,5,6,7,8], 4);

In [5]:
a = [1,2,3,4,5,6,7,8]
b = [1,4,6,7]
def setminus(a, b):
    return [i for i in a if not(i in b)]



In [15]:
for b in combinations(range(1,17), 8):
    c = setminus(range(1,17), b)
    if (sum(b) == sum(c) and 
    (sum([i*i for i in b]) == sum([i*i for i in c])) and
     sum([i*i*i for i in b]) == sum([i*i*i for i in c])):
        print(b)


(2, 3, 5, 8, 9, 12, 14, 15)
(1, 4, 6, 7, 10, 11, 13, 16)


In [16]:
def ThueMorse(n):
    if (n==1):
        return ([1])
    prev=ThueMorse(n-1)
    inv = setminus(range(1,2**(n-1)+1), prev)
    return (prev+[i + 2**(n-1) for i in  inv])

In [17]:
ThueMorse(4)

[1, 4, 6, 7, 10, 11, 13, 16]

In [18]:
def CheckProuhetTarryEscott(n):
    b = ThueMorse(n)
    c = setminus(range(1, 2**n+1), b)
#    print(b, c)
    for m in range(1,n):
        if(sum([i**m for i in b]) != sum([i**m for i in c])):
            return False
    return True

CheckProuhetTarryEscott(15)

    

True

In [1]:
## タイル張り

In [25]:
import numpy as np
x =np.array([[-1, 1, 2,2],
          [1,1,3,2],
          [4,3,3,5],
          [4,4,5,5]])
np.max(x)

5

## タイリング

$2 \times 2$ の正方形から1つ小さな正方形を除いた，大きさ3のブロックを考える。
このブロックを$2^n \times 2^n$ の正方形にひき詰めようとしても，無理である。（なぜか？）

$2^n \times 2^n$ の正方形から 1 つ任意の単位正方形を除いた，$2^n \times 2^n - 1$  の
大きさの領域なら，数だけをみたら，敷き詰められる可能性がある。（なぜか？）

実際に，任意の n >1 において，また，任意の1つの単位正方形の選び方において，敷き詰めが可能である。
そのことは，次のようにして数学的帰納法で証明できる。まず，n = 2 では可能である。
n で可能な時，$2^{n+1} \times 2^{n+1}$ の正方形から1つの単位正方形を除いた図形が
与えられたとする。これを，4 つの$2^n \times 2^n$ の正方形成分の集まりと見た時，その一つだけに，
一つの単位正方形がぬけている。このぬけている成分のところに欠けた部分がくるように，ど真ん中に一つブロックを
を配置する。すると，4つの$2^n \times 2^n$成分は，それぞれが1つづつぬけた状態になる。よって，
帰納法の仮定により，これらはブロックで敷き詰められる。このようにして，全体がブロックで敷き詰められる。

さて，この証明に従った形で，ブロックの敷き詰めを行おう。敷き詰めには，int の ndarray を用いて，
抜けた部分は -1 で，各ブロックは同じ数を用いて表そう。例えば，次は一つの敷き詰めである。0 は，まだ置かれていないことを表すのにとっておこう。


In [2]:
import numpy as np
x =np.array([[-1, 1, 2,2],
          [1,1,3,2],
          [4,3,3,5],
          [4,4,5,5]])
print(x)
print(np.max(x))

[[-1  1  2  2]
 [ 1  1  3  2]
 [ 4  3  3  5]
 [ 4  4  5  5]]
5


**練習問題** 上の問題で，1つは敷き詰めがあることが分かったが，それぞれの n と単位ブロックの位置に対して，何種類の敷き詰めがあるだろうか。再帰的な手続きは，このようなしらみつぶし的な探索に有効である。数え上げの方法を考えよう。

In [ ]:
$f_a(x) = ax(1-x)$